# Generated by Django 4.0.4 on 2022-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
