# Generated by Django 4.0.5 on 2022-06-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_rename_fname_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pic1',
            field=models.FileField(default='avtar.png', upload_to='seller profile'),
        ),
        migrations.AddField(
            model_name='seller',
            name='pic2',
            field=models.FileField(default='avtar.png', upload_to='seller profile'),
        ),
    ]
