# Generated by Django 4.0.5 on 2022-06-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_pic1_seller_pic2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pic2',
        ),
        migrations.AddField(
            model_name='product',
            name='pic1',
            field=models.FileField(default='avtar.png', upload_to='seller profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.FileField(default='avtar.png', upload_to='seller profile'),
        ),
    ]
