# Generated by Django 4.0.4 on 2022-06-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_discountedprice'),
        ('seller', '0006_remove_seller_pic1_remove_seller_pic2_product_pic1_and_more'),
    ]

    operations = [
    ]
