# Generated by Django 4.0.4 on 2022-06-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_order_user_remove_orderdetails_order_and_more'),
        ('seller', '0008_remove_product_discountedprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
